description: >
    Implement to provide InfiniBand attributes of a network interface. Objects
    that implement this interface also implement
    xyz.openbmc_project.Inventory.Item.NetworkInterface.

    This interface corresponds to the InfiniBand object of the Redfish
    NetworkDeviceFunction resource.
properties:
    - name: PermanentNodeGUID
      type: string
      description: >
          The permanent node GUID assigned to this network interface in four
          groups of four hexadecimal digits separated by colons, as InfiniBand
          notates a GUID. Example: F0FB:7F03:00A4:2B64
    - name: PermanentPortGUID
      type: string
      description: >
          The permanent port GUID assigned to this network interface in four
          groups of four hexadecimal digits separated by colons, as InfiniBand
          notates a GUID. Example: F0FB:7F03:00A4:2B64
