description: >
    Implement to provide Chassis attributes.

properties:
    - name: Type
      type: enum[self.ChassisType]
      default: Unknown
      description: >
          The type of physical form factor of the chassis.

enumerations:
    - name: ChassisType
      description: >
          Possible chassis type
      values:
          - name: Blade
            description: >
                An enclosed or semi-enclosed, typically vertically-oriented,
                system chassis that must be plugged into a multi-system chassis
                to function normally.
          - name: Component
            description: >
                A small chassis, card, or device that contains devices for a
                particular subsystem or function.
          - name: Enclosure
            description: >
                A generic term for a chassis that does not fit any other
                description.
          - name: Module
            description: >
                A small, typically removable, chassis or card that contains
                devices for a particular subsystem or function.
          - name: RackMount
            description: >
                A single-system chassis designed specifically for mounting in an
                equipment rack.
          - name: StandAlone
            description: >
                A single, free-standing system, commonly called a tower or
                desktop chassis.
          - name: StorageEnclosure
            description: >
                A chassis that encloses storage.
          - name: Unknown
            description: >
                An unknown chassis type.
          - name: Zone
            description: >
                A logical division or portion of a physical chassis that
                contains multiple devices or systems that cannot be physically
                separated.

associations:
    - name: powered_by
      description: >
          Objects that implement Chassis can optionally implement the
          'powered_by' association to provide a link to one or more power
          supplies.
      reverse_name: powering
      required_endpoint_interfaces:
          - xyz.openbmc_project.Inventory.Item.PowerSupply
    - name: chassis_for
      description: >
          Objects that implement Chassis can optionally implement the 'assembly'
          association to provide a link to one or more inventory items. These
          inventory items will be modeled as Assemblies under the Chasssis.
      reverse_name: assembly_for
      required_endpoint_interfaces:
          - xyz.openbmc_project.Inventory.Item.Vrm
          - xyz.openbmc_project.Inventory.Item.Battery
          - xyz.openbmc_project.Inventory.Item.Tpm
          - xyz.openbmc_project.Inventory.Item.Panel
          - xyz.openbmc_project.Inventory.Item.DiskBackplane
