description: >
    Implement to provide Chassis attributes.

properties:
    - name: Type
      type: enum[self.ChassisType]
      default: Unknown
      description: >
          The type of physical form factor of the chassis.

enumerations:
    - name: ChassisType
      description: >
          Possible chassis type
      values:
          - name: Component
            description: >
                A small chassis, card, or device that contains devices for a
                particular subsystem or function.
          - name: Enclosure
            description: >
                A generic term for a chassis that does not fit any other
                description.
          - name: Module
            description: >
                A small, typically removable, chassis or card that contains
                devices for a particular subsystem or function.
          - name: RackMount
            description: >
                A single-system chassis designed specifically for mounting in an
                equipment rack.
          - name: StandAlone
            description: >
                A single, free-standing system, commonly called a tower or
                desktop chassis.
          - name: StorageEnclosure
            description: >
                A chassis that encloses storage.
          - name: Unknown
            description: >
                An unknown chassis type.
          - name: Zone
            description: >
                A logical division or portion of a physical chassis that contains
                multiple devices or systems that cannot be physically separated.

associations:
    - name: attached_cables
      description: >
          Objects that implement Chassis can optionally implement the
          attached_cables association to provide a link to one or more
          cables.
      reverse_names:
        - downstream_chassis
        - upstream_chassis
      required_endpoint_interfaces:
        - xyz.openbmc_project.Inventory.Item.Cable
    - name: contains
      description: >
           Objects that implement Chassis can optionally implement the contains
           association to provide a link to another chassis.
      reverse_names:
        - containedBy
      required_endpoint_interfaces:
        - xyz.openbmc_project.Inventory.Item.Chassis
    - name: containedBy
      description: >
        Objects that implement Chassis can optionally implement the containedBy
        association to provide a link to another chassis.
      reverse_names:
        - contains
      required_endpoint_interfaces:
        - xyz.openbmc_project.Inventory.Item.Chassis
    - name: processors
      description: >
        Objects that implement Chassis can optionally implement the processors
        association to provide a link to one or more processors.
      reverse_names:
        - chassis
      required_endpoint_interfaces:
        - xyz.openbmc_project.Inventory.Item.Cpu
    - name: memories
      description: >
        Objects that implement Chassis can optionally implement the processors
        association to provide a link to memories.
      reverse_names:
        - chassis
      required_endpoint_interfaces:
        - xyz.openbmc_project.Inventory.Item.Dimm
    - name: pcie_slots
      description: >
        Objects that implement Chassis can optionally implement the processors
        association to provide a link to one or more PCIe slots.
      reverse_names:
        chassis
      required_endpoint_interfaces:
        - xyz.openbmc_project.Inventory.Item.PCIeSlot
    - name: memories
      description: >
        Objects that implement Chassis can optionally implement the processors
        association to provide a link to memories.
      reverse_names:
        - chassis
      required_endpoint_interfaces:
        - xyz.openbmc_project.Inventory.Item.Dimm
    - name: poweredby
      description: >
        Objects that implement Chassis can optionally implement the processors
        association to provide a link to one or more power supply unit
      reverse_names:
        chassis
      required_endpoint_interfaces:
        - xyz.openbmc_project.Inventory.Item.PowerSupply
