description: >
    Implement to provide drive attributes.

properties:
    - name: Type
      default: Unknown
      type: enum[self.DriveType]
      description: >
          The type of physical form factor of the Drive.

enumerations:
    - name: DriveType
      description: >
          Possible Drive type
      values:
          - name: HDD
            description: >
                A hard disk drive is an electro-mechanical data storage device
                that stores and retrieves digital data using magnetic storage.
          - name: SSD
            description: >
                A solid-state drive is a solid-state storage device that uses
                integrated circuit assemblies to store data persistently.
          - name: Unknown
            description: >
                The Drive type is unknown.
