description: >
    Implement to provide Fan attributes.

associations:
    - name: cooling
      description: >
          Objects that implement Fan can optionally implement the 'cooling'
          association to provide a link back to one or more Items. In case the
          Fan is cooling a Chassis, that can be used to fill `CoolingChassis`
          property in Redfish (Fan schema).
      reverse_name: cooled_by
      required_endpoint_interfaces:
          - xyz.openbmc_project.Inventory.Item
    - name: contained_by
      description: >
          Objects that implement Fan can optionally implement the 'contained_by'
          association to provide a link back to at most one Chassis. This
          association then determines Resource placement in the Redfish
          implementation.
      reverse_name: containing
      required_endpoint_interfaces:
          - xyz.openbmc_project.Inventory.Item.Chassis
