description: >
    Implement to provide Fan attributes.

associations:
    - name: fanning
      description: >
          Objects that implement Fan can optionally implement the
          'fanning' association to provide a link back to a Chassis.
      reverse_name: fanned_by
      required_endpoint_interfaces:
          - xyz.openbmc_project.Inventory.Item.Chassis
    - name: identifying
      description: >
          Objects that implement Fan can optionally implement the 'identifying'
          association to provide a link back to a LED.
      reverse_name: identified_by
      required_endpoint_interfaces:
          - xyz.openbmc_project.Led.Group
    - name: faulting
      description: >
          Objects that implement Fan can optionally implement the 'faulting'
          association to provide a link back to a LED.
      reverse_name: faulted_by
      required_endpoint_interfaces:
          - xyz.openbmc_project.Led.Group