description: >
    Implement to provide Fan attributes.

properties:
    - name: MaxRatedRPM
      type: int32
      default: 0
      description: >
          Max RPM that the fan is rated for. A value of 0 implies the max RPM is
          unknown or unavailable.
      flags:
          - readonly

associations:
    - name: cooling
      description: >
          Objects that implement Fan can optionally implement the 'cooling'
          association to provide a link back to a Item.
      reverse_name: cooled_by
      required_endpoint_interfaces:
          - xyz.openbmc_project.Inventory.Item
