description: >
    Implement to provide network interface attributes.

    In InfiniBand mode this interface corresponds to the InfiniBand object of
    the Redfish NetworkDeviceFunction resource.
properties:
    - name: MACAddress
      type: string
      description: >
          MAC address of the item
    - name: PermanentNodeGUID
      type: string
      description: >
          The permanent node GUID assigned to this network interface in four
          groups of four hexadecimal digits separated by hyphens, most
          significant group first. Example: 0002-C903-00AB-CDEF
    - name: PermanentPortGUID
      type: string
      description: >
          The permanent port GUID assigned to this network interface in four
          groups of four hexadecimal digits separated by hyphens, most
          significant group first. Example: 0002-C903-00AB-CDEF

associations:
    - name: produced_by
      description: >
          Objects that implement NetworkInterface can optionally implement the
          produced_by association to provide a link back to a PCIe function.
      reverse_name: producing
      required_endpoint_interfaces:
          - xyz.openbmc_project.Inventory.Item.PCIeFunction

    - name: exposed_by
      description: >
          Objects that implement NetworkInterface can optionally implement the
          exposed_by association to provide a link back to the physical
          NetworkAdapter that exposes this logical network function.
      reverse_name: exposing
      required_endpoint_interfaces:
          - xyz.openbmc_project.Inventory.Item.NetworkAdapter

    - name: assigned_to
      description: >
          Objects that implement NetworkInterface can optionally implement the
          assigned_to association to list the physical port connectors on which
          this logical network function operates.
      reverse_name: assigning
      required_endpoint_interfaces:
          - xyz.openbmc_project.Inventory.Connector.Port
