description: >
    This defines a PCIe device to be exposed for system management.  It includes
    the device properties and function properties for all 8 possible functions
    that are needed for the device identification.

properties:
    - name: DeviceType
      type: string
      description: >
          Indicates if the device is MultiFunction or SingleFunction.
    - name: GenerationInUse
      type: enum[xyz.openbmc_project.Inventory.Item.PCIeSlot.Generations]
      default: "Unknown"
      description: >
          The PCIe interface generation in use by the device.
    - name: GenerationSupported
      type: enum[xyz.openbmc_project.Inventory.Item.PCIeSlot.Generations]
      default: "Unknown"
      description: >
          The maximum PCIe generation supported by the device.
    - name: MaxLanes
      type: size
      default: 0
      description: >
          The maximum number of PCIe lanes supported by the PCIe Device
    - name: LanesInUse
      type: size
      default: maxint
      description: >
          The number of PCIe lanes in use by this device. Default value of
          maxint is to accommodate the situation where the value of this
          property is not known due to some unknown reason, like hardware
          failure. The value of 0 indicates that the link is not active.

associations:
    - name: upstream_pcie_slot
      description: >
          Objects that implement PCIeDevice can optionally implement the
          upstream_pcie_slot association to provide a link back to a PCIe slot.
      reverse_names:
          - associated_pcie_device
      required_endpoint_interfaces:
          - xyz.openbmc_project.Inventory.Item.PCIeSlot
