description: >
    Implement to provide PowerSupply attributes.

properties:
    - name: PowerCapacityWatts
      type: uint64
      default: 0
      description: >
          The maximum rated power output capacity of this power supply in Watts.
          `0` if it cannot be determined.

associations:
    - name: powering
      description: >
          Objects that implement PowerSupply can optionally implement the
          'powering' association to provide a link back to a Item.
      reverse_name: powered_by
      required_endpoint_interfaces:
          - xyz.openbmc_project.Inventory.Item
