description: >
    Implement to provide PowerSupply attributes.

associations:
    - name: powering
      description: >
          Objects that implement PowerSupply can optionally implement the
          'powering' association to provide a link back to a Chassis.
      reverse_name: powered_by
      required_endpoint_interfaces:
          - xyz.openbmc_project.Inventory.Item.Chassis
    - name: identified_by
      description: >
          Objects that implement PowerSupply can optionally implement the
          'identified_by' association to provide a link back to a LED.
      reverse_name: identifying
      required_endpoint_interfaces:
          - xyz.openbmc_project.Led.Group
