description: >
    Helper interface to construct interface names in entity-manager. (provide
    prefix of the interface name)

    Use this interface to mark an object as configuration if the real
    configuration interface cannot be defined in PDI.
