description: >
    Implement to advertise power and frequency attributes of a single available
    (but not necessarily active/applied) processor configuration profile.
properties:
    - name: ConfigId
      type: int32
      description: Configuration profile identifier.
      flags:
        - readonly
    - name: BaseSpeedMhz
      type: int32
      description: The base clock speed of the processor in MHz.
      flags:
        - readonly
    - name: BaseSpeedPrioritySettings
      type: array[dict[string, variant[int32, array[int32]]]]
      description: >
        An array of objects that specify the clock speed for sets of cores when
        the configuration is operational. Each entry contains the following keys:
          BaseSpeedMHz: The clock speed to configure the set of cores in MHz.
          CoreCount: The number of cores to configure with the speed specified
            by BaseSpeedMHz.
          CoreIDs: An array identifying the cores to configure with the speed
            specified by the BaseSpeedMHz. Length of the array shall equal the
            value of CoreCount.
      flags:
        - readonly
    - name: MaxJunctionTemperatureCelsius
      type: int32
      description: The maximum temperature of the junction in degrees Celsius.
      flags:
        - readonly
    - name: MaxSpeedMhz
      type: int32
      description: >
        The maximum clock speed to which the processor can be configured in MHz.
      flags:
        - readonly
    - name: TdpWatts
      type: int32
      description: The thermal design point of the processor in watts.
      flags:
        - readonly
    - name: TotalAvailableCoreCount
      type: int32
      description: The number of cores in the processor that can be configured.
      flags:
        - readonly
    - name: TurboProfile
      type: array[dict[string, int32]]
      description: >
        An array of objects that specify the turbo profile for a set of active
        cores. Each entry contains the following keys:
          ActiveCoreCount: The number of cores to be configured with the maximum
            turbo clock speed
          MaxSpeedMHz: The maximum turbo clock speed that corresponds to the
            number of active cores in MHz.
      flags:
        - readonly
