description: >
    Implement to provide basic item attributes.  Required by all objects
    within the inventory namespace.

    Any service implementing Inventory.Item on one or more objects must
    implement org.freedesktop.DBus.ObjectManager on
    /xyz/openbmc_project/inventory.

properties:
    - name: PrettyName
      type: string
      description: >
          The human readable name of the item.
    - name: Present
      type: boolean
      description: >
          Whether or not the item is present.
