description: >
    Implement to provide basic item attributes.  Required by all objects within
    the inventory namespace.

    Any service implementing Inventory.Item on one or more objects must
    implement org.freedesktop.DBus.ObjectManager on
    /xyz/openbmc_project/inventory.

properties:
    - name: PrettyName
      type: string
      description: >
          The human readable name of the item.
    - name: Present
      type: boolean
      description: >
          Whether or not the item is present.

associations:
    - name: containing
      description: >
          Any inventory Items (usually Boards or Chassis) can optionally
          implement the 'containing' association to provide one or more links to
          Items which it physically contains.
      reverse_name: contained_by
      required_endpoint_interfaces:
          - xyz.openbmc_project.Inventory.Item
    - name: contained_by
      description: >
          Any inventory Items can optionally implement the 'contained_by'
          association to provide a link to exactly one Item (usually a Board or
          Chassis) which physically contains it.
      reverse_name: containing
      required_endpoint_interfaces:
          - xyz.openbmc_project.Inventory.Item
    - name: sensors
      description: >
          Sensors may implement an 'inventory' to 'sensors' association with the
          inventory item related to it.
      reverse_names:
          - inventory
      required_endpoint_interfaces:
          - xyz.openbmc_project.Sensor.Value
    - name: cooled_by
      description: >
          Objects that implement Item can optionally implement the 'cooled_by'
          association to provide a link to one or more fans.
      reverse_name: cooling
      required_endpoint_interfaces:
          - xyz.openbmc_project.Inventory.Item.Fan
    - name: identified_by
      description: >
          Objects that implement Item can optionally implement the
          'identified_by' association to provide a link to one or more LED
          Groups.
      reverse_name: identifying
      required_endpoint_interfaces:
          - xyz.openbmc_project.Led.Group
    - name: fault_identified_by
      description: >
          Objects that implement Item can optionally implement the
          'fault_identified_by' association to provide a link to one or more LED
          Groups.
      reverse_name: fault_identifying
      required_endpoint_interfaces:
          - xyz.openbmc_project.Led.Group
    - name: powered_by
      description: >
          Objects that implement Item can optionally implement the 'powered_by'
          association to provide a link to one or more power supplies.
      reverse_name: powering
      required_endpoint_interfaces:
          - xyz.openbmc_project.Inventory.Item.PowerSupply
    - name: measured_by
      description: >
          Objects that implement Item can optionally implement the 'measured_by'
          association to provide a link to one or more metrics.
      reverse_name: measuring
      required_endpoint_interfaces:
          - xyz.openbmc_project.Metrics
