description: >
    Implement to provide basic item attributes.  Required by all objects
    within the inventory namespace.

    Any service implementing Inventory.Item on one or more objects must
    implement org.freedesktop.DBus.ObjectManager on
    /xyz/openbmc_project/inventory.

properties:
    - name: PrettyName
      type: string
      description: >
          The human readable name of the item.
    - name: Present
      type: boolean
      description: >
          Whether or not the item is present.

associations:
    - name: sensors
      description: >
          Sensors may implement an 'inventory' to 'sensors' association with
          the inventory item related to it.
      reverse_names:
          - inventory
      required_endpoint_interfaces:
          - xyz.openbmc_project.Sensor.Value
    - name: identified_by
      description: >
          Objects that implement PowerSupply can optionally implement the
          'identified_by' association to provide a link back to a LED.
      reverse_name: identifying
      required_endpoint_interfaces:
          - xyz.openbmc_project.Led.Group