description: >
    Implement to provide memory metrics attributes.
properties:
    - name: BlockSizeBytes
      type: uint64
      description: >
          Block size in bytes of all structure elements.
    - name: BandwidthPercent
      type: uint64
      description: >
          Bandwith utilization as percentage.