description: >
    Implement to provide general backplan attributes. A backplan is a group of
    electrical connectors in parallel with each other, so that each
    pin of each connector is linked to the same relative pin of all the other
    connectors, forming a computer bus.
