description: >
    Implement to provide item physical asset attributes.
properties:
    - name: PartNumber
      type: string
      description: >
          The item part number, typically a stocking number.
    - name: SerialNumber
      type: string
      description: >
          The item serial number.
    - name: Manufacturer
      type: string
      description: >
          The item manufacturer.
    - name: BuildDate
      type: string
      description: >
          The date of item manufacture in ISO 8601 format, either as
          YYYYMMDD or YYYYMMDDhhmmss.
    - name: Model
      type: string
      description: >
          The model of the item.
