description: >
    Implement to indicate an item with a defined CLEI number.

properties:
    - name: CLEINumber
      type: string
      description: >
          The CLEI number of the inventory item.
