description: >
    Implement to provide physical dimension attributes.

properties:
    - name: HeightMm
      type: double
      description: >
          The height in millimeters.
    - name: WidthMm
      type: double
      description: >
          The width in millimeters.
    - name: DepthMm
      type: double
      description: >
          The depth in millimeters.
