description: >
    Implement to provide physical dimension attributes.

properties:
    - name: Height
      type: double
      description: >
          The height in millimeters.
    - name: Width
      type: double
      description: >
          The width in millimeters.
    - name: Depth
      type: double
      description: >
          The depth in millimeters.
