description: >
    Implement to define extended manufacturing data for inventory items.

properties:
    - name: ExtendedMFGData
      type: dict[string, string]
      description: >
          A dictionary of manufacturer-specific extended data fields, which
          may contain fields such as manufacturing plant, lot number, etc.
