description: >
    Implement to provide item versioning attributes.
properties:
    - name: Version
      type: string
      description: >
          The item version.

# vim: tabstop=8 expandtab shiftwidth=4 softtabstop=4
