description: >
    Implement to provide information which needs to be published at
    system level.
    All the properties which are applicable to the complete system
    instead of individual FRUs can be published under this interface.
properties:
    - name: Brand
      type: string
      description: >
          The brand value, used to identify the system.
