description: >
    This defines DHCP client configuration.
properties:
    - name: DNSEnabled
      type: boolean
      description: >
          if true then the DNS servers received from the DHCP server will be
          used and take precedence over any statically configured ones.
    - name: NTPEnabled
      type: boolean
      description: >
          if true then the NTP servers received from the DHCP server will be
          used by systemd-timesyncd and take precedence over any statically
          configured ones.
    - name: HostNameEnabled
      type: boolean
      description: >
          if true then the hostname received from the DHCP server will be set as
          the transient hostname of the system.
    - name: DomainEnabled
      type: boolean
      description: >
          if true then the domain names received from the DHCP server will be
          used by systemd-resolved and take precedence over any statically
          configured ones.
    - name: SendHostNameEnabled
      type: boolean
      description: >
          if true then DHCP option 12 is enabled i.e machine`s hostname will be
          sent to the DHCP server.

          sent to the DHCP server.
    - name: VendorClassIdentifier
      type: string
      description: >
          The vendor class identifier used to identify vendor type and configuration.
      errors:
          - xyz.openbmc_project.Common.Error.NotAllowed

methods:
    - name: SetVendorOption
      parameters:
        - name: option
          type: uint32
        - name: value
          type: string
      returns:
        - name: result
          type: int16
      description: >
          Set vendor DHCP vendor option and value
    - name: GetVendorOption
      parameters:
        - name: option
          type: uint32
      returns:
        - name: result
          type: string
      description: >
          Get vendor DHCP vendor value by option
    - name: DelVendorOption
      parameters:
        - name: option
          type: uint32
      returns:
        - name: result
          type: int16
      description: >
          Delete vendor DHCP vendor value by option
