description: >
    Implement to provide system specific network configuration features.
properties:
    - name: HostName
      type: string
      description: >
          The value of this property shall be host name of the system.
    # Deprecating these "DefautGateway" and "DefaultGateway6" properties.
    # These are no longer needed, as default gateway is configured per
    # Ethernet interface, but need to keep here as IBM Hypervisor uses them.
    - name: DefaultGateway
      type: string
      description: >
          Default IPv4 gateway of the system.
      errors:
          - xyz.openbmc_project.Common.Error.InvalidArgument
          - xyz.openbmc_project.Common.Error.NotAllowed
    - name: DefaultGateway6
      type: string
      description: >
          Default IPv6 gateway of the system.
      errors:
          - xyz.openbmc_project.Common.Error.InvalidArgument
          - xyz.openbmc_project.Common.Error.NotAllowed
