description: >
    Implement to provide hardware accelerator attributes. A hardware
    accelerator used to perform some functions more efficiently than is
    possible in software running on a general-purpose CPU. Examples of
    possible hardware accelerators include: GPUs, FPGAs, and ASICs.

properties:
    - name: Type
      type: enum[self.AcceleratorType]
      default: 'Unknown'
      type: string
      description: >
          The type of accelerator.

enumerations:
    - name: AcceleratorType
      description: >
          Possible accelerator type
      values:
        - name: 'Accelerator'
          description: >
              An accelerator.
        - name: 'CPU'
          description: >
              A CPU.
        - name: 'Core'
          description: >
              A core in a processor.
        - name: 'DSP'
          description: >
              A DSP.
        - name: 'FPGA'
          description: >
              An FPGA.
        - name: 'GPU'
          description: >
              A GPU.
        - name: 'OEM'
          description: >
              An OEM-defined processing unit.
        - name: 'Thread'
          description: >
              "A thread in a processor."
        - name: 'Unknown'
          description: >
              Unknown type
