description: >
    Implement to provide Chassis attributes.

properties:
    - name: Type
      type: string
      description: >
          Chassis type (values from SMBUS spec)

# vim: tabstop=8 expandtab shiftwidth=4 softtabstop=4
