description: >
    Implement to provide Chassis attributes.

properties:
    - name: Type
      type: string
      description: >
          The type of physical form factor of the chassis.

# vim: tabstop=8 expandtab shiftwidth=4 softtabstop=4
