description: >
    Implement to enable voltage configuration for the item.
properties:
    - name: Controls
      type: a{sv}
      description: >
          A colection of properties to control voltage
          and power parameters.

# vim: tabstop=8 expandtab shiftwidth=4 softtabstop=4
