description: >
    This defines DHCP client configuration.
properties:
    - name: DNS
      type: boolean
      description: >
          if true then the DNS servers received from the DHCP server
          will be used and take precedence over any statically configured ones.
    - name: NTP
      type: boolean
      description: >
          if true then the NTP servers received from the DHCP server
          will be used by systemd-timesyncd and take precedence over any
          statically configured ones.
    - name: HostName
      type: boolean
      description: >
          if true then the hostname received from the DHCP server
          will be set as the transient hostname of the system.
