description: >
    Implement to provide system specific network configuration features.
    An object implementing this interface must implement
    xyz.openbmc_project.Collection,
    xyz.openbmc_project.Object.Delete.
properties:
    - name: HostName
      type: string
      description: >
          The value of this property shall be host name of the system.
    - name: DefaultGateway
      type: string
      description: >
          default gateway of the system.
    - name: Nameservers
      type: array[string]
      description: >
          DNS servers on the system.
