description: >
    Implement to provide system specific network configuration features.
properties:
    - name: HostName
      type: string
      description: >
          The value of this property shall be host name of the system.
    - name: DefaultGateway
      type: string
      description: >
          default gateway of the system.
    - name: VendorClassIdentifier
      type: string
      description: >
          The vendor class identifier used to identify vendor type
          and configuration.
