description: >
    Interface to describe the presence of a cable, fan board or any other
    device. The primary use-case for now is for gpio presence detection for a
    gpio hardware inventory.

properties:
    - name: Name
      type: string
      description: >
          Used by entity-manager to identify which hw was detected. For internal
          use by entity-manager. Fictional examples are
          'com.meta.Hardware.Yv4.cable0', 'com.meta.Hardware.Yv4.Fanboard0',
          'com.vendorX.Hardware.BoardY.LeakDetector3'. The name should be
          namespaced with dots to avoid collision, according to documented
          Hardware enumerations like
          https://github.com/openbmc/phosphor-dbus-interfaces/blob/6a8507d06e172d8d29c0459f0a0d078553d2ecc7/yaml/com/meta/Hardware/BMC.interface.yaml
