description: >
    Provides Remote BIOS configuration management functionality.
    As communication to this service is done through authenticated
    & authorized session, there won't be any validation for both.

methods:
    - name: GetAllAttributes
      description: >
          To get all the BIOS attributes.
      returns:
        - name: AttributesData
          type: dict[string,struct[array[string],variant[boolean,byte,uint32,uint64,string],variant[boolean,byte,uint32,uint64,string],dict[string,variant[boolean,byte,uint32,uint64,string]]]]
          description: >
              map{attributename,struct{array{valuetype,displayname,description,pagePtr},
              currentvalue,defaultvalue,array{map{optionstring,optionvalue}}}}
      errors:
        - xyz.openbmc_project.Common.Error.InternalFailure
        - xyz.openbmc_project.Common.Error.InvalidArgument

    - name: SetAllAttributes
      description: >
          To set all the BIOS attributes.
      parameters:
        - name: AttributesData
          type: dict[string,struct[array[string],variant[boolean,byte,uint32,uint64,string],variant[boolean,byte,uint32,uint64,string],dict[string,variant[boolean,byte,uint32,uint64,string]]]]
          description: >
              map{attributename,struct{array{valuetype,displayname,description,pagePtr},
              currentvalue,defaultvalue,array{map{optionstring,optionvalue}}}}
      errors:
        - xyz.openbmc_project.Common.Error.InternalFailure
        - xyz.openbmc_project.Common.Error.InvalidArgument

    - name: SetAttribute
      description: >
          To set the new value on new or existing attribute name.
      parameters:
         - name: AtributeName
           type: string
           description: >
               AttributeName which has to be changed.
         - name: AttributeValue
           type: array[byte]
           description: >
               New attribute value
      errors:
        - xyz.openbmc_project.Common.Error.InternalFailure
        - xyz.openbmc_project.BIOSConfig.Common.Error.AttributeNotSettable
        - xyz.openbmc_project.BIOSConfig.Common.Error.InvalidValue
        - xyz.openbmc_project.BIOSConfig.Common.Error.AttributeNotFound

    - name: GetAttribute
      description: >
          To get the attribute value of existing attributes.
      parameters:
         - name: AtributeName
           type: string
           description: >
               To get the bios attribute current values and pending values if available.
      returns:
        - name: CurrentValue
          type: array[byte]
          description: >
              The attribute current value.
        - name: PendingValue
          type: array[byte]
          description: >
              The pending attribute value if its available.
        - name: AttributeValueType
          type: enum[self.AttributeType]
          description: >
              PLDM attribute Type present in PLDM spec
      errors:
        - xyz.openbmc_project.Common.Error.InternalFailure
        - xyz.openbmc_project.BIOSConfig.Common.Error.AttributeNotFound

    - name: GetPendingAttributes
      description: >
          To get the attribute value of Pending attributes.
      returns:
        - name: Pendinglist
          type: dict[string,variant[boolean,byte,uint32,uint64,string]]
          description: >
              The Pending attribute name and new value.
      errors:
        - xyz.openbmc_project.Common.Error.InternalFailure
        - xyz.openbmc_project.BIOSConfig.Common.Error.AttributeNotFound


    - name: SetPayload
      description: >
           Create the payload object and store the payload data.
           Mainly,Its used for transfer the bulk payload data.
      parameters:
        - name: PayloadTransferState
          type: enum[self.PayloadTState]
          description: >
             Payload transfer status
        - name: PayloadType
          type: enum[self.PayloadType]
          description: >
             Payload transfer status
        - name: ReservationID
          type: uint32
          description: >
             Reservation ID generated in StartTransfer.
             Used to identify the sender.
        - name: PayloadVersion
          type: uint16
          description: >
             Payload version
        - name: PayloadOffset
          type: uint32
          description: >
             Payload Offset
        - name: PayloadDataSize
          type: uint32
          description: >
             Payload data size
        - name: PayloadChecksum
          type: uint32
          description: >
             Payload data checksum
        - name: PayloadTotalSize
          type: uint32
          description: >
             Total Payload data size
        - name: PayloadTotalChecksum
          type: uint32
          description: >
             Total Payload checksum
        - name: Data
          type: array[byte]
          description: >
             Payload data
      returns:
        - name: ResponseData
          type: uint32
          description: >
              For StartTransfer,return will be Current Reservation ID.
              For InProgress, return will be Actual data recevied.
              For EndTransfer, return will be Total Payload received

      errors:
        - xyz.openbmc_project.Common.Error.InternalFailure
        - xyz.openbmc_project.Common.Error.InvalidArgument
        - xyz.openbmc_project.BIOSConfig.Common.Error.InvalidChecksum
        - xyz.openbmc_project.BIOSConfig.Common.Error.InvalidPayloadType
        - xyz.openbmc_project.BIOSConfig.Common.Error.TransferInComplete

    - name: UpdatePayloadFileInfo
      description: >
           To update the payload information in RBC daemon
           RBC daemon will create the payload object for this.
      parameters:
        - name: PayloadType
          type: enum[self.PayloadType]
          description: >
             Payload type
        - name: FilePath
          type: string
          description: >
             File path
        - name: FileVersion
          type: uint16
          description: >
             File version
        - name: FileSize
          type: uint32
          description: >
             size of File
        - name: FileChkSum
          type: uint32
          description: >
             File checksum32

      errors:
        - xyz.openbmc_project.Common.Error.InternalFailure
        - xyz.openbmc_project.Common.Error.InvalidArgument
        - xyz.openbmc_project.BIOSConfig.Common.Error.InvalidChecksum
        - xyz.openbmc_project.BIOSConfig.Common.Error.InvalidPayloadType

properties:

    - name: RBCCapability
      type: int32
      description: >
           Contain RBC capabilities flags
           Ex: PLDM based or IPMI based
           Ex: Immediate/ Deffered model

signals:

    - name: ResetBIOSSettings
      description: >
         Signal indicating reset BIOS settings request from user.
      properties:
         - name: ResetFlag
           type: enum[self.ResetFlag]
           description: >
             Reset BIOS setting type requested by user.

    - name: AttributeChanged
      description: >
         Signal indicating the particular attribute is changed.
      properties:
         - name: AtributeName
           type: string
           description: >
            Particular attribute name is changed.
         - name: AtributeValue
           type: array[byte]
           description: >
            Attribute new value.

enumerations:
    - name: ResetFlag
      description: >
        Reset BIOS setting type requested by user.
      values:
        - name: FactoryDefaults
          description: >
            Used to set factory default settings.
        - name: FailSafeDefaults
          description: >
            Used to set the fail safe settings.

    - name: PayloadType
      description: >
        Payload Types.
      values:
        - name: IntelXMLType0
          description: >
            proprietary XML payload contain all attributes details.
        - name: IntelXMLType1
          description: >
            Intel proprietary payload contain changed attribute name and value pair.
        - name: AttributeRegistry
          description: >
            Stringified JSON - Attribute registry format.
        - name: AttributeStringTable
          description: >
            PLDM BIOS string table.
        - name: AttributeNameTable
          description: >
            PLDM BIOS Attribute name table.
        - name: AttributeValueTable
          description: >
            PLDM BIOS Attribute value table.
        - name: AttributePendingTable
          description: >
            PLDM Attribute pending Value table.

    - name: AttributeType
      description: >
        Attribute value types based on PLDM spec
      values:
        - name: BIOSEnumeration
          description: >
            BIOSEnumeration represents a BIOS attribute that
            can have a value from a set of possible values.
        - name: BIOSString
          description: >
            BIOSString represents a string that the BIOS uses
        - name: BIOSPassword
          description: >
             the password encoding type
        - name: BIOSInteger
          description: >
            BIOSInteger represents a BIOS integer
        - name: BIOSBootConfigSetting
          description: >
            BIOSBootConfigSetting represents a boot configuration setting
            that includes information about the boot sources
        - name: BIOSCollection
          description: >
            BIOSCollection represents a collection of the BIOS attributes.
        - name: BIOSConfigSet
          description: >
            BIOSConfigSet represents the types of BIOS configuration sets
            that the BIOS supports.
        - name: BIOSEnumerationReadOnly
          description: >
            ReadOnly BIOSEnumeration type
        - name: BIOSStringReadOnly
          description: >
            ReadOnly BIOS string type
        - name: BIOSPasswordReadOnly
          description: >
            ReadOnly BIOS Password.type.
        - name: BIOSIntegerReadOnly
          description: >
            ReadOnly BIOS integer type.
        - name: BIOSBootConfigSettingReadOnly
          description: >
            ReadOnly boot configuration settings.
        - name: BIOSCollectionReadOnly
          description: >
            ReadOnly collection of the BIOS attributes.
        - name: BIOSConfigSetReadOnly
          description: >
            ReadOnly types of BIOS configuration sets
            that the BIOS supports.


    - name: PayloadTState
      description: >
        Payload and Payload transfer status
      values:
        - name: StartTransfer
          description: >
            Used to start the Payload transfer in setPayload
        - name: InProgress
          description: >
            Used to indicate the payload transfer in progress in setPayload
        - name: EndTransfer
          description: >
            Used to indicate end of the payload transfer in setPayload
        - name: UserAbort
          description: >
            Used to abort the current payload transfer in setPayload

# vim: tabstop=8 expandtab shiftwidth=4 softtabstop=4
