description: >
    Provides Remote BIOS configuration management functionality.
    As communication to this service is done through authenticated
    & authorized session, there won't be any validation for both.

methods:
    - name: GetAllAttributes
      description: >
          To get all the BIOS attributes.
      parameters:
        - name: Attributeformat
          type: enum[self.AttributesModel]
          description: >
            Attributes fetch type-All attributeRegistry format details or
            Attribute name:value pairs list in JSON format(All / Only Pending list).
      returns:
        - name: Attributes
          type: string
          description: >
              Stringified JSON values of BIOS attributes.
              AttributeRegistry format or name:value pair list
      errors:
        - xyz.openbmc_project.Common.Error.InternalFailure
        - xyz.openbmc_project.Common.Error.InvalidArgument

    - name: SetAttribute
      description: >
          To set the new attribute value on existing attribute name.
      parameters:
         - name: AtributeName
           type: array[byte]
           description: >
               AttributeName which has to be changed.
         - name: AttributeValue
           type: array[byte]
           description: >
               New attribute value
      errors:
        - xyz.openbmc_project.Common.Error.InternalFailure
        - xyz.openbmc_project.BIOSConfig.Common.Error.AttributeNotSettable
        - xyz.openbmc_project.BIOSConfig.Common.Error.InvalidValue
        - xyz.openbmc_project.BIOSConfig.Common.Error.AttributeNotFound

    - name: GetAttribute
      description: >
          To get the attribute value of existing attributes.
      parameters:
         - name: AtributeName
           type: array[byte]
           description: >
               To get the bios attribute current values and pending values if available.
      returns:
        - name: CurrentValue
          type: array[byte]
          description: >
              The attribute current value.
        - name: PendingValue
          type: array[byte]
          description: >
              The pending attribute value if its available.
        - name: AttributeValueType
          type: byte
      errors:
        - xyz.openbmc_project.Common.Error.InternalFailure
        - xyz.openbmc_project.BIOSConfig.Common.Error.AttributeNotFound

    - name: SetPayload
      description: >
           Create the payload object and store the payload data.
           Mainly,Its used for send bunk data in raw binary format.
      parameters:
        - name: PayloadTransferState
          type: enum[self.PayloadTState]
          description: >
             Payload transfer status
        - name: PayloadType
          type: enum[self.PayloadType]
          description: >
             Payload transfer status
        - name: ReservationID
          type: uint32
          description: >
             Reservation ID generated in StartTransfer.
             Used to identify the sender.
        - name: PayloadVersion
          type: uint16
          description: >
             Payload version
        - name: PayloadOffset
          type: uint32
          description: >
             Payload Offset
        - name: PayloadDataSize
          type: uint32
          description: >
             Payload data size
        - name: PayloadChecksum
          type: uint32
          description: >
             Payload data checksum
        - name: PayloadTotalSize
          type: uint32
          description: >
             Total Payload data size
        - name: PayloadTotalChecksum
          type: uint32
          description: >
             Total Payload checksum
        - name: Data
          type: array[byte]
          description: >
             Payload data
      returns:
        - name: ResponseData
          type: uint32
          description: >
              For StartTransfer,return will be Current Reservation ID.
              For InProgress, return will be Actual data recevied.
              For EndTransfer, return will be Total Payload received

      errors:
        - xyz.openbmc_project.Common.Error.InternalFailure
        - xyz.openbmc_project.Common.Error.InvalidArgument
        - xyz.openbmc_project.BIOSConfig.Common.Error.InvalidChecksum
        - xyz.openbmc_project.BIOSConfig.Common.Error.InvalidPayloadType
        - xyz.openbmc_project.BIOSConfig.Common.Error.TransferInComplete

    - name: UpdatePayloadFileInfo
      description: >
           To update the payload information in RBC daemon
           RBC daemon will create the payload object for this.
      parameters:
        - name: PayloadType
          type: enum[self.PayloadType]
          description: >
             Payload type
        - name: FilePath
          type: string
          description: >
             File path
        - name: FileVersion
          type: uint16
          description: >
             File version
        - name: FileSize
          type: uint32
          description: >
             size of File
        - name: FileChkSum
          type: uint32
          description: >
             File checksum32

      errors:
        - xyz.openbmc_project.Common.Error.InternalFailure
        - xyz.openbmc_project.Common.Error.InvalidArgument
        - xyz.openbmc_project.BIOSConfig.Common.Error.InvalidChecksum
        - xyz.openbmc_project.BIOSConfig.Common.Error.InvalidPayloadType

properties:

    - name: RBCCapability
      type: int32
      description: >
           Contain RBC capabilities flags
           Ex: PLDM based or IPMI based
           Ex: Immediate/ Deffered model

signals:

    - name: ResetBIOSSettings
      description: >
         Signal indicating reset BIOS settings request from user.
      properties:
         - name: ResetFlag
           type: enum[self.ResetFlag]
           description: >
             Reset BIOS setting type requested by user.

    - name: AttributeChanged
      description: >
         Signal indicating the particular attribute is changed.
      properties:
         - name: AtributeName
           type: array[byte]
           description: >
            Particular attribute name is changed.
         - name: AtributeValue
           type: array[byte]
           description: >
            Attribute new value.

enumerations:
    - name: AttributesModel
      description: >
        The Attribute retrieval format
      values:
        - name: Attributeslist
          description: >
            Used to get all attributes list name:value pair information of BIOS configuration.
        - name: AttributesRegistry
          description: >
            Used to get the whole attribute registry information of BIOS.
            It contain all attributes with all detailed information like default
            value, current value, supported value, dependency.
            (i.e) Redfish AttributeRegistry schema Format
        - name: PendingAttributelist
          description: >
            Used to retreive Pending attribute name:value pairs list.
            In JSON form, name: new value pairs list.

    - name: ResetFlag
      description: >
        Reset BIOS setting type requested by user.
      values:
        - name: FactoryDefaults
          description: >
            Used to set factory default settings.
        - name: FailSafeDefaults
          description: >
            Used to set the fail safe settings.

    - name: PayloadType
      description: >
        Payload Types.
      values:
        - name: IntelXMLType0
          description: >
            proprietary XML payload contain all attributes details.
        - name: IntelXMLType1
          description: >
            Intel proprietary payload contain changed attribute name and value pair.
        - name: AttributeRegistry
          description: >
            Stringified JSON - Attribute registry format.
        - name: AttributeStringTable
          description: >
            BIOS string table.
        - name: AttributeNameTable
          description: >
           BIOS Attribute name table.
        - name: AttributeValueTable
          description: >
            BIOS Attribute value table.
        - name: AttributePendingTable
          description: >
            Attribute pending table.

    - name: PayloadStatus
      description: >
        Payload / File status
      values:
        - name: Unknown
          description: >
            File / Payload status is unknown or not set
        - name: Valid
          description: >
            valid status is set  by BIOS config daemon based on  checksum verification
        - name: Corrupted
          description: >
            corrupted status is set  by BIOS config daemon based on
            total size, checksum verification

    - name: PayloadTState
      description: >
        Payload and Payload transfer status
      values:
        - name: StartTransfer
          description: >
            Used to start the Payload transfer in setPayload
        - name: InProgress
          description: >
            Used to indicate the payload transfer in progress in setPayload
        - name: EndTransfer
          description: >
            Used to indicate end of the payload transfer in setPayload
        - name: UserAbort
          description: >
            Used to abort the current payload transfer in setPayload

# vim: tabstop=8 expandtab shiftwidth=4 softtabstop=4
