description: >
    Interface to manage LLDP settings, to enable or disable LLDP packet
    transmission for a network interface.

properties:
    - name: EnableLLDP
      type: boolean
      default: false
      description: >
          Enables or disables LLDP packet transmission for a network interface.
