description: >
    Implement to provide CPU attributes.
properties:
    - name: EC
      type: s
      description: >
          Engineering Change level of the item.

# vim: tabstop=8 expandtab shiftwidth=4 softtabstop=4
