description: >
    Implement to provide Asset Tag. The asset tag is used to uniquely identify
    the object.
properties:
    - name: AssetTag
      type: string
      description: >
          The tag provided to an object to identify it.

