description: >
    Implement to indicate item availability changes.
properties:
    - name: Cached
      type: boolean
      description: >
          Whether or not the item is cached.  When true, the item and its
          remaining attributes are undefined.
