description: >
    Implement to provide physical dimension attributes.

properties:
    - name: Height
      type: double
      description: >
          The height in meters.
    - name: Width
      type: double
      description: >
          The width in meters.
    - name: Depth
      type: double
      description: >
          The depth in meters.
