description: >
    Holds the position of an inventory item when it's necessary to distinguish
    it from other inventory items of the same type.
properties:
    - name: Position
      type: size
      default: maxint
      description: >
          The position.
