description: >
    Implement to provide the SKU (stock-keeping unit) of an inventory item.
properties:
    - name: SKU
      type: string
      description: >
          The stock-keeping unit number of the inventory item.
      default: ""
