description: >
    Indicates the thermal management path through the chassis.
properties:
    - name: ThermalDirection
      type: enum[self.ThermalDirection]
      default: Unknown
      description: >
          This property shall indicate the general direction of the thermal
           management path through the chassis.

enumerations:
    - name: ThermalDirection
      description: >
          Possible airflow direction
      values:
          - name: BackToFront
            description: >
                A chassis with the air intake in the back and exhaust out the
                front.
          - name: FrontToBack
            description: >
                A chassis with the air intake in the front and exhaust out the
                back.
          - name: Sealed
            description: >
                A sealed chassis with no air pathway.
          - name: TopExhaust
            description: >
                A chassis with air exhaust on the top.
          - name: Unknown
            description: >
                A default type for Airflow direction.
